package nestedternary.project.database.schema;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nestedternary.project.database.schema.BinLocations;

import nestedternary.project.database.schema.BinLocationsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig binLocationsDaoConfig;

    private final BinLocationsDao binLocationsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        binLocationsDaoConfig = daoConfigMap.get(BinLocationsDao.class).clone();
        binLocationsDaoConfig.initIdentityScope(type);

        binLocationsDao = new BinLocationsDao(binLocationsDaoConfig, this);

        registerDao(BinLocations.class, binLocationsDao);
    }
    
    public void clear() {
        binLocationsDaoConfig.getIdentityScope().clear();
    }

    public BinLocationsDao getBinLocationsDao() {
        return binLocationsDao;
    }

}
